### EGEOFFREY ###

### define base image
ARG ARCHITECTURE
FROM $ARCHITECTURE/python:3.5-alpine

### define workdir
ENV WORKDIR=/egeoffrey
WORKDIR $WORKDIR

### install dependencies
RUN apk update && apk add jq nano tzdata ca-certificates && rm -rf /var/cache/apk/*
RUN pip3 install paho-mqtt requests tinynumpy pyyaml yq apscheduler

### install eGeoffrey SDK
COPY . $WORKDIR

### define entrypoint
ENTRYPOINT ["sh", "docker-entrypoint.sh"]
CMD ["egeoffrey"]
