### EGEOFFREY ###

### define base image
FROM balenalib/rpi-raspbian

### define workdir
ENV WORKDIR=/egeoffrey 
WORKDIR $WORKDIR

### install dependencies
RUN apt-get update && apt-get install -y nano curl wget unzip python python-pip python-setuptools python3 python3-pip python3-setuptools expect net-tools usbutils raspi-config raspi-gpio wiringpi libraspberrypi-bin libusb-1.0.0-dev build-essential autoconf cmake pkg-config libtool python-dev libyaml-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade "pip < 21.0"
RUN pip install paho-mqtt requests tinynumpy pyyaml yq apscheduler
RUN pip3 install paho-mqtt requests tinynumpy pyyaml yq apscheduler

### install eGeoffrey SDK
COPY . $WORKDIR

### define entrypoint
ENTRYPOINT ["bash", "docker-entrypoint.sh"]
CMD ["egeoffrey"]
